# Generated by Django 3.1.7 on 2021-04-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.URLField(blank=True, max_length=2048, null=True)),
                ('series_title', models.CharField(blank=True, max_length=254, null=True)),
                ('released_year', models.CharField(blank=True, max_length=4, null=True)),
                ('certificate', models.CharField(blank=True, max_length=3, null=True)),
                ('runtime', models.CharField(blank=True, max_length=8, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('meta_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('star1', models.CharField(blank=True, max_length=50, null=True)),
                ('star2', models.CharField(blank=True, max_length=50, null=True)),
                ('star3', models.CharField(blank=True, max_length=50, null=True)),
                ('star4', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('gross', models.CharField(blank=True, max_length=50, null=True)),
                ('dvd_stock', models.IntegerField(blank=True, null=True)),
                ('bluray_stock', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
