# Generated by Django 3.1.7 on 2021-04-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.URLField(blank=True, max_length=2048, null=True)),
                ('Series_Title', models.CharField(blank=True, max_length=254, null=True)),
                ('Released_Year', models.CharField(blank=True, max_length=4, null=True)),
                ('Certificate', models.CharField(blank=True, max_length=3, null=True)),
                ('Runtime', models.CharField(blank=True, max_length=8, null=True)),
                ('Genre', models.CharField(blank=True, max_length=20, null=True)),
                ('IMDB_Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('Overview', models.TextField(blank=True, null=True)),
                ('Meta_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Director', models.CharField(blank=True, max_length=50, null=True)),
                ('Star1', models.CharField(blank=True, max_length=50, null=True)),
                ('Star2', models.CharField(blank=True, max_length=50, null=True)),
                ('Star3', models.CharField(blank=True, max_length=50, null=True)),
                ('Star4', models.CharField(blank=True, max_length=50, null=True)),
                ('No_of_Votes', models.PositiveIntegerField(blank=True, null=True)),
                ('Gross', models.CharField(blank=True, max_length=50, null=True)),
                ('dvd_stock', models.IntegerField(blank=True, null=True)),
                ('bluray_stock', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
