# Generated by Django 3.1.7 on 2021-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
