# Generated by Django 3.1.7 on 2021-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20210424_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Certificate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
