# Generated by Django 3.1.7 on 2021-04-13 18:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_add1', models.CharField(max_length=80)),
                ('delivery_add2', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_town', models.CharField(max_length=40)),
                ('delivery_county', models.CharField(blank=True, max_length=80, null=True)),
                ('delivery_postcode', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_country', django_countries.fields.CountryField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
