# Generated by Django 3.1.7 on 2021-04-17 11:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_add1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_add2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_town',
            field=models.CharField(default='', max_length=40),
        ),
    ]
