# Generated by Django 3.1.7 on 2021-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210417_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.TextField(default=''),
        ),
    ]
